version: 2.1

executors:
  linux:
    machine:
      image: ubuntu-2204:current
    environment:
      architecture: "amd64"
      platform: "linux/amd64"

orbs:
  maven: circleci/maven@2.1.1

workflows:
  maven_test:
    jobs:
      - maven/test:
          executor: linux
